### ISSUE TITLE
能发一下chrome的字体设置吗

### ISSUE THREAD

**Issue by brucmao** [subframe7536/UserScript#1]
目前我是这样设置的，跟你的效果图有点不一样
![image](https://user-images.githubusercontent.com/6119652/187582365-9ee0fcb1-a6c3-4973-8c1d-77c4f29c1dd2.png)

![image](https://user-images.githubusercontent.com/6119652/187582327-c652570b-a87e-445e-ab99-9c2be8934dde.png)

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/187582644-a4b6dc02-ea1f-453f-b8a7-dd7a89f4cab3.png)

**Comment by brucmao** [comment]
感谢，再打扰下，苹方圆这个字体网上没有搜到，全称是什么呢，或者能提供一份吗

**Comment by subframe7536** [comment]
...[善用搜索](https://buhuibaidu.me/?s=%E8%8B%B9%E6%96%B9%E5%9C%86)
