### ISSUE TITLE
将chrome界面语言设置为英文，渲染失效

### ISSUE THREAD

**Issue by brucmao** [subframe7536/UserScript#2]
中文界面

![Snipaste_2022-09-13_08-50-02](https://user-images.githubusercontent.com/6119652/189783932-32d03092-5e57-42b3-bf1f-96ce8a22e9c1.png)
英文界面

![Snipaste_2022-09-13_08-52-45](https://user-images.githubusercontent.com/6119652/189783955-b160a5bf-371e-4171-a56f-c16ee8f59c0b.png)

**Comment by subframe7536** [comment]
这...我这边没法复现...

**Comment by brucmao** [comment]
我win11安装的也是英文版，不知道有没有关系

**Comment by subframe7536** [comment]
我没有写任何关于页面语言匹配的css...可能是用了主题导致样式被覆盖了，配置里自行修改一下吧

**Comment by brucmao** [comment]
我禁用了所有扩展，油猴脚本也只开这个脚本，取消v2ex自定义样式，发现chrome 使用中文，英文界面语言渲染确实不一样
英文
![Snipaste_2022-09-16_10-17-56](https://user-images.githubusercontent.com/6119652/190542349-2118141c-95a8-420f-b872-f01c6dd7dec2.png)
中文
![Snipaste_2022-09-16_10-18-25](https://user-images.githubusercontent.com/6119652/190542381-98bd1de1-9501-4f95-ab52-66142353128c.png)
字体设置（没找到你的苹方圆）
![image](https://user-images.githubusercontent.com/6119652/190542644-0021d19c-9247-4736-90c3-7ad19f6c1b39.png)

**Comment by subframe7536** [comment]
用[暴力猴](https://violentmonkey.github.io/)试试？

**Comment by brucmao** [comment]
暴力猴也一样的,chrome英文
![image](https://user-images.githubusercontent.com/6119652/203045783-a96835a2-1d19-47cd-a244-2f36df4561a0.png)
chrome中文
![image](https://user-images.githubusercontent.com/6119652/203045856-81debbd5-d89d-4d67-bfc8-f4d74e240890.png)

**Comment by subframe7536** [comment]
刚刚我也复现了，发现似乎只有v2ex才会出现这种问题，而且指定了字体名称而非sans-serif就能正常显示了

**Comment by brucmao** [comment]
我目前发现gmail邮件列表也有这样的问题，在哪里指定字体名称呢
英文
![image](https://user-images.githubusercontent.com/6119652/203053755-eb336aae-ecdf-4eb2-8c99-e144cca12bd4.png)
中文
![image](https://user-images.githubusercontent.com/6119652/203054104-28cfb5b8-4a7f-414e-8cd1-50f21d01ec7f.png)

**Comment by subframe7536** [comment]
脚本全局替换，sans-serif => 你要的ui字体，monospace => 你要的代码字体

**Comment by subframe7536** [comment]
https://v2ex.com/t/901385 可以看看这个
