### ISSUE TITLE
twitter 无法加载用户的全部tweets

### ISSUE THREAD

**Issue by brucmao** [subframe7536/UserScript#3]
开启这个油猴脚本后，访问 https://twitter.com/ycombinator
只能加载部分推文，无法查看该用户的全部内容（已排除其他扩展和油猴脚本，只开启这个脚本）
![Snipaste_2022-09-16_09-20-10](https://user-images.githubusercontent.com/6119652/190543215-b1e2914b-7326-417e-9a17-ca0bc2af9889.png)

**Comment by subframe7536** [comment]
滚动条问题，兼容性比较差，后来改回去了，这里没更新

现在已更新

**Comment by brucmao** [comment]
测试通过，感谢
