### ISSUE TITLE
英文使用简写 ’距离过大

### ISSUE THREAD

**Issue by brucmao** [subframe7536/UserScript#4]
复制出来应该是中文的分号？

![image](https://user-images.githubusercontent.com/6119652/195763178-6a42266b-caa9-421c-94c7-7cac978bb480.png)
https://thepythoncodingbook.com/2022/10/11/exploring-python-functions-through-experimentation/

**Comment by subframe7536** [comment]
中英文的单双引号是同一个，我为了看中文舒服一些就选了宽版的引号
