### ISSUE TITLE
代码预览显示从4变为2

### ISSUE THREAD

**Issue by msclock** [subframe7536/UserScript#6]
如图所示，python代码正常缩进为4，github/gitlab显示为2
![image](https://github.com/subframe7536/UserScript/assets/43399351/4a25776f-231b-40aa-b727-9b7627d76095)

**Comment by subframe7536** [comment]
强制刷新一下

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/UserScript/assets/78338239/7edaf8ab-05b5-49fb-a937-26e46390c83b)
打开devtools，应该在body上看到这个

**Comment by msclock** [comment]
@subframe7536 我尽可能设置了字体参数，还是无效，请问是需要如何设置才能到达body的样式和你一样，我通过配置设置字体效果和你给的截图不一样
![image](https://github.com/subframe7536/UserScript/assets/43399351/7847f21b-74a9-4118-91c1-a906166e9840)

![image](https://github.com/subframe7536/UserScript/assets/43399351/b88ea301-dedf-41d3-8a17-71ee94113844)

![image](https://github.com/subframe7536/UserScript/assets/43399351/a785737a-565b-4364-8e38-c0aef5768aad)

**Comment by subframe7536** [comment]
试试 删除然后重新安装
如果还是不行，就先回退到 v1.0.36，v1.1 主要是实现字体切换到热更新，我把实现方式优化一下

**Comment by subframe7536** [comment]
gitlab 我没有使用过，待会儿看一下

**Comment by msclock** [comment]
@subframe7536 v1.0.36 正常显示👍

**Comment by subframe7536** [comment]
过几天优化一下实现方式

**Comment by subframe7536** [comment]
试试 v1.1.12

**Comment by msclock** [comment]
> 试试 v1.1.12

问题仍然存在🤣，我还是用1.0.36吧

**Comment by subframe7536** [comment]
能不能截一下[这张图](https://github.com/subframe7536/maple-font/blob/375e4f2dc96b2dd2e2e999cd53b57cd93bf4af77/source/build.py#L14-L20)，我看看能不能复现

![image](https://github.com/subframe7536/UserScript/assets/78338239/4f4fa1a5-5236-4bd1-84d3-5e7afd1eb0b6)

**Comment by msclock** [comment]
> 能不能截一下[这张图](https://github.com/subframe7536/maple-font/blob/375e4f2dc96b2dd2e2e999cd53b57cd93bf4af77/source/build.py#L14-L20)，我看看能不能复现
> 
> ![image](https://private-user-images.githubusercontent.com/78338239/308383799-4f4fa1a5-5236-4bd1-84d3-5e7afd1eb0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODMwNDAsIm5iZiI6MTcwOTA4Mjc0MCwicGF0aCI6Ii83ODMzODIzOS8zMDgzODM3OTktNGY0ZmExYTUtNTIzNi00YmQxLTg0ZDMtNWU3YWZkMWViMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxMTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNWI2NjM3YTcxMmUwNWI0OGZjNWE4YTc4MzI4NjIxMmUyNDI2OTE3ZTllNWYwNjkyYmJmZDUxYzRkZjY5YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I1Ee8FxT9_wb-ytlyJL_JAbnNv8txXuHp6tH2zos4D4)

如图：
![image](https://github.com/subframe7536/UserScript/assets/43399351/f3a32784-21d0-4e4e-9fc2-442418d58f3c)

字体配置：
![image](https://github.com/subframe7536/UserScript/assets/43399351/af2e9450-d086-489d-8fab-e8eae391ce83)

![image](https://github.com/subframe7536/UserScript/assets/43399351/a216c6ce-54ea-4eff-b4a4-89ef7f73f49e)

**Comment by subframe7536** [comment]
浏览器的monospace字体已经设置过了吗，看上去是字体的问题

**Comment by msclock** [comment]
> 浏览器的monospace字体已经设置过了吗，看上去是字体的问题

重新设置插件字体：
sans-serif: sans-serif,maple ui
monspace: monospace,maple ui,sans-serif

Edge 字体设置
![image](https://github.com/subframe7536/UserScript/assets/43399351/9a7bae90-d2d1-4c8c-90cd-544f9a92a09f)


以上配置仍然仍然未生效

**Comment by subframe7536** [comment]
“等宽字体”设置为 Maple Mono 或者 Jetbrains Mono 或者 Fira Code，Maple UI 不是等宽字体

**Comment by msclock** [comment]
> “等宽字体”设置为 Maple Mono 或者 Jetbrains Mono 或者 Fira Code，Maple UI 不是等宽字体

正常了🤣感谢，配置如下：
![image](https://github.com/subframe7536/UserScript/assets/43399351/d357b9bd-f1cd-416b-baea-5a60737f0344)
