### ISSUE TITLE
请教一下能否实现移入可滚动区域才显示滚动条，移出就不显示

### ISSUE THREAD

**Issue by johnsonwong666** [subframe7536/UserScript#8]
该效果作用于 页面所有可滚动容器

**Comment by subframe7536** [comment]
部分可以：https://github.com/subframe7536/obsidian-theme-maple/blob/main/src/workspace/scrollbar.scss

但是高版本浏览器自带了

**Comment by johnsonwong666** [comment]
> 部分可以：https://github.com/subframe7536/obsidian-theme-maple/blob/main/src/workspace/scrollbar.scss
> 
> 但是高版本浏览器自带了

感谢回复 可以在哪里看到示例效果吗

**Comment by subframe7536** [comment]
`chrome://flag/` 开启 `Fluent Overlay scrollbars` `Fluent scrollbars`

**Comment by johnsonwong666** [comment]
感谢回复。https://github.com/subframe7536/obsidian-theme-maple/blob/main/src/workspace/scrollbar.scss 

这个样式可以在什么地方看到预览呢？

**Comment by subframe7536** [comment]
https://github.com/subframe7536/obsidian-theme-maple?tab=readme-ov-file#scrollbar-style
