### ISSUE TITLE
滚动条的自定义宽度经常会失效，得打开脚本设置一下才生效，刷新页面又没了。

### ISSUE THREAD

**Issue by leic4u** [subframe7536/UserScript#9]
大部分页面都是没生效的，手动设置一下，当时能生效。

再刷新页面有小概率能够继续生效，大部分时候是刷新就失效了。

**Comment by subframe7536** [comment]
我这边一切正常，你的浏览器版本是？还有列举一些不生效的网站

**Comment by leic4u** [comment]
> 我这边一切正常，你的浏览器版本是？还有列举一些不生效的网站

浏览器：`版本 125.0.6422.77（正式版本） （64 位）`
插件：`Tampermonkey beta v5.1.6194` 对了，油猴我改了注入模式为即时。
滚动条宽度配置是`max(0.25vw,4px)`

已经关闭过所有插件（只保留 Tampermonkey 和 ZeroOmega），所有脚本都关闭（只保留本脚本）来测试过了，还是会稳定复现。

V2EX 基本每次打开都是失效的。
Github 现在这条 issue 的页面是生效的（因为是我在打字过程中出的滚动条，刚进来页面时没有滚动条），Github 其他页面（一打开页面就加载滚动条的那种页面）也是失效的。

**Comment by subframe7536** [comment]
Windows 的 Chrome?
高版本的 Chrome 在一些玄学的情况下不支持滚动条宽度设置

**Comment by leic4u** [comment]
是的，Windows 的 Chrome 最新版本。

神奇的是，我另一台 Windows 电脑，浏览器版本一致，油猴版本一致，滚动条宽度一致，居然是正常的。不管哪个页面打开都是生效状态。

两台电脑的 Chrome 的 `chrome://flag/` 我都开了 `Overlay Scrollbars` `Fluent Overlay scrollbars.` `Fluent scrollbars.` 这三个选项为 `Enabled`。

邪门了。

**Comment by subframe7536** [comment]
还有一点，有些情况下 color-schema 对某个页面的某几个滚动条是不生效的😅

**Comment by subframe7536** [comment]
可能windows版本也有关系。。。

**Comment by subframe7536** [comment]
> 两台电脑的 Chrome 的 `chrome://flag/` 我都开了 `Overlay Scrollbars` `Fluent Overlay scrollbars.` `Fluent scrollbars.` 这三个选项为 `Enabled`。

`Overlay Scrollbars` 应该是被 `Fluent Overlay scrollbars` 覆盖的

**Comment by leic4u** [comment]
这个问题是不是暂时没法排查。。。

**Comment by subframe7536** [comment]
是的，就挺玄学的

**Comment by leic4u** [comment]
> 是的，就挺玄学的

那可以单独关闭滚动条美化么，只保留字体美化。

（因为我试了下安装 隐形滚动条 这个插件，结果会被你的插件覆盖，它那边设置的就没法生效。所以想把这边的关掉，用那边的设置。）

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/UserScript/assets/78338239/580575b6-47db-45be-b73f-dfc10e5c02c1)

**Comment by leic4u** [comment]
> ![image](https://private-user-images.githubusercontent.com/78338239/333619911-580575b6-47db-45be-b73f-dfc10e5c02c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjAxODMsIm5iZiI6MTcxNjU1OTg4MywicGF0aCI6Ii83ODMzODIzOS8zMzM2MTk5MTEtNTgwNTc1YjYtNDdkYi00NWJlLWI3M2YtZGZjMTBlNWMwMmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE0MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYjc4OWU2YzNkOTZmYjQ3MTIwZTRiMTgxNmJlYjQwOTQ0NWJjNTk1MGI4YTZhMWUzYjFlMjM1MmU4MmViNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sylcfFDfjlHq_KSJd_C50evXjaRg2v0mRgTVSRs7FA4)

🤣不好意思，眼瞎了。居然没注意到第一个就是。😂
